sudo: false
language: python
python:
    - "3.5"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run test
script:
    - make test
    - coverage run test_algorithm.py
    - codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN
